### ISSUE TITLE
multiplex chokes on byte 0xe2?

### ISSUE THREAD

**Issue by eMPee584** [dankilman/multiplex#26]
Strangely, there seems to be an issue handling this byte stream [hotplug-autorun.without-multiplex.log](https://github.com/dankilman/multiplex/files/10299738/hotplug-autorun.without-multiplex.log), it results in this error:

```
Traceback (most recent call last):
  File "/mnt/stix/usb-live-linux/scripts/hotplug-autorun", line 193, in <module>
    main()
  File "/mnt/stix/usb-live-linux/scripts/hotplug-autorun", line 181, in main
    mp.run()
  File "/usr/lib/python3/dist-packages/multiplex/multiplex.py", line 25, in run
Loop <_UnixSelectorEventLoop running=False closed=True debug=False> that handles pid 583160 is closed
    asyncio.run(self.run_async(load))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/usr/lib/python3/dist-packages/multiplex/multiplex.py", line 46, in run_async
    await self.viewer.run()
  File "/usr/lib/python3/dist-packages/multiplex/viewer.py", line 186, in run
    await self._main()
  File "/usr/lib/python3/dist-packages/multiplex/viewer.py", line 208, in _main
    async for obj, output in streamer:
  File "/usr/lib/python3/dist-packages/aiostream/stream/advanced.py", line 59, in base_combine
    result = task.result()
  File "/usr/lib/python3/dist-packages/multiplex/viewer.py", line 270, in _wrapped_iterator
    async for elem in iterator:
  File "/usr/lib/python3/dist-packages/multiplex/iterator.py", line 200, in g
    async for data in s:
  File "/usr/lib/python3/dist-packages/aiostream/stream/advanced.py", line 59, in base_combine
    result = task.result()
  File "/usr/lib/python3/dist-packages/multiplex/iterator.py", line 34, in stream_reader_generator
    yield b.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe2 in position 5034: unexpected end of data
```
Any idea? :thinking:

**Comment by dankilman** [comment]
I'm not sure what encoding the actual output should be in (i.e. how to decode).
I did however just release a new version (0.6.1) to address this issue by gracefully replacing output `decode` failed at
so you can update `multiplex` by whatever means you use to do so
